name: release_repos
on:
  release:
    types: [created]

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  RELEASE_NOTES: "create release on agent repo"

jobs:
  release-repos:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Update version file
      run: echo $GITHUB_REF_NAME > VERSION.md
    - name: Release kxdroid/k8s-watcher
      run: gh release create -R kxdroid/k8s-watcher ${{ github.REF_NAME }} --notes "${{ env.RELEASE_NOTES }}"
